"""Generate book table

Revision ID: ca9ff790a603
Revises: 6b9e3cb0f200
Create Date: 2025-08-13 19:02:19.254293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca9ff790a603'
down_revision: Union[str, None] = '6b9e3cb0f200'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('bk_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bk_name', sa.String(), nullable=False),
    sa.Column('author_name', sa.String(), nullable=False),
    sa.Column('bk_summary', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('bk_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    # ### end Alembic commands ###
